# Generated by Django 3.0.4 on 2020-09-29 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='timeslot',
            field=models.CharField(choices=[], max_length=64),
        ),
    ]
