# Generated by Django 3.0.4 on 2020-09-29 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_auto_20200929_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='timeslot',
            field=models.CharField(choices=[('afternoon', 'Afternoon'), ('evening', 'Evening'), ('writing', 'Writing Evening')], max_length=64),
        ),
    ]
